import { describe, expect, test, beforeAll } from "bun:test";
import { AnonymousSubmissionService } from "../src/services/anonymous-submission.service";
import { Client, AccountId, PrivateKey, TopicMessageQuery } from "@hiero-ledger/sdk";
import dotenv from "dotenv";

dotenv.config({ path: "../.env" });

describe("Anonymous Submission Test", () => {
  let service: AnonymousSubmissionService;
  let client: Client;

  beforeAll(() => {
    const operatorId = process.env.HEDERA_OPERATOR_ID;
    const operatorKey = process.env.HEDERA_OPERATOR_KEY;
    const topicId = process.env.HEDERA_TOPIC_COMPLAINTS;

    if (!operatorId || !operatorKey || !topicId) {
      throw new Error("Missing .env variables (ID, KEY, or TOPIC).");
    }

    console.log(`\n Connecting to Hedera (${process.env.HEDERA_NETWORK})...`);
    
    service = new AnonymousSubmissionService();

    client = Client.forName(process.env.HEDERA_NETWORK || "mainnet");
    client.setOperator(
        AccountId.fromString(operatorId),
        operatorKey.startsWith("302e") ? PrivateKey.fromStringDer(operatorKey) : PrivateKey.fromString(operatorKey)
    );
  });

  test("Should successfully write an anonymous complaint to HCS", async () => {
    console.log("📤 Attempting to submit transaction...");

    const mockData = {
      userId: "internal-db-uuid-123",
      anonymousIdentifier: "anon_test_runner_001",
      title: "Integration Test Complaint",
      text: "This is a test message generated by the Bun test runner.",
      category: "testing",
      area: "Cairo Test Lab",
      incidentDate: new Date(),
      evidenceCids: ["QmTestHash1", "QmTestHash2"]
    };

    const result = await service.submitAnonymousComplaint(mockData);

    console.log(`Transaction id: ${result.transactionId}`);
    console.log(`Sequence Number:  ${result.topicSequenceNumber}`);

    expect(result.success).toBe(true);
    expect(result.status).toBe("success");
    expect(result.transactionId).toBeDefined();
    
    // Critical check sequence number must be a string number (e.g. "5", "6")
    expect(result.topicSequenceNumber).toBeDefined();
    expect(parseInt(result.topicSequenceNumber)).toBeGreaterThan(0);
  }, 30000); 

  test("Should fail gracefully if environment is missing", () => {
    const oldTopic = process.env.HEDERA_TOPIC_COMPLAINTS;

    delete process.env.HEDERA_TOPIC_COMPLAINTS;

    try {
      new AnonymousSubmissionService();
    } catch (e: any) {
      expect(e.message).toContain("Missing required Hedera environment");
    }

    process.env.HEDERA_TOPIC_COMPLAINTS = oldTopic;
  });
});