version: 1
build:
    main: cmd/sawtakd
    proto:
        path: proto
accounts:
    - name: admin
      coins:
        - 10000000000000usawtak
    - name: ministry
      coins:
        - 50000usawtak
    - name: university
      coins:
        - 50000usawtak
    - name: ngo
      coins:
        - 50000usawtak
    - name: elysia_relayer
      coins:
        - 10000000usawtak
client:
    typescript:
        path: ts-client
default_denom: usawtak
validators:
    - name: admin
      bonded: 10000000000usawtak
