// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: sawtak/sawtak/v1/complaint.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sawtak.sawtak.v1";

/** Complaint defines the Complaint message. */
export interface Complaint {
  id: number;
  trackingId: string;
  anonymousIdentifier: string;
  complaintType: string;
  title: string;
  text: string;
  category: string;
  area: string;
  directedTo: string;
  incidentDate: string;
  evidence: string;
  status: string;
}

function createBaseComplaint(): Complaint {
  return {
    id: 0,
    trackingId: "",
    anonymousIdentifier: "",
    complaintType: "",
    title: "",
    text: "",
    category: "",
    area: "",
    directedTo: "",
    incidentDate: "",
    evidence: "",
    status: "",
  };
}

export const Complaint: MessageFns<Complaint> = {
  encode(message: Complaint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.trackingId !== "") {
      writer.uint32(18).string(message.trackingId);
    }
    if (message.anonymousIdentifier !== "") {
      writer.uint32(26).string(message.anonymousIdentifier);
    }
    if (message.complaintType !== "") {
      writer.uint32(34).string(message.complaintType);
    }
    if (message.title !== "") {
      writer.uint32(42).string(message.title);
    }
    if (message.text !== "") {
      writer.uint32(50).string(message.text);
    }
    if (message.category !== "") {
      writer.uint32(58).string(message.category);
    }
    if (message.area !== "") {
      writer.uint32(66).string(message.area);
    }
    if (message.directedTo !== "") {
      writer.uint32(74).string(message.directedTo);
    }
    if (message.incidentDate !== "") {
      writer.uint32(82).string(message.incidentDate);
    }
    if (message.evidence !== "") {
      writer.uint32(90).string(message.evidence);
    }
    if (message.status !== "") {
      writer.uint32(98).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Complaint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComplaint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.trackingId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.anonymousIdentifier = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.complaintType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.area = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.directedTo = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.incidentDate = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.evidence = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Complaint {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      trackingId: isSet(object.trackingId)
        ? globalThis.String(object.trackingId)
        : isSet(object.tracking_id)
        ? globalThis.String(object.tracking_id)
        : "",
      anonymousIdentifier: isSet(object.anonymousIdentifier)
        ? globalThis.String(object.anonymousIdentifier)
        : isSet(object.anonymous_identifier)
        ? globalThis.String(object.anonymous_identifier)
        : "",
      complaintType: isSet(object.complaintType)
        ? globalThis.String(object.complaintType)
        : isSet(object.complaint_type)
        ? globalThis.String(object.complaint_type)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      area: isSet(object.area) ? globalThis.String(object.area) : "",
      directedTo: isSet(object.directedTo)
        ? globalThis.String(object.directedTo)
        : isSet(object.directed_to)
        ? globalThis.String(object.directed_to)
        : "",
      incidentDate: isSet(object.incidentDate)
        ? globalThis.String(object.incidentDate)
        : isSet(object.incident_date)
        ? globalThis.String(object.incident_date)
        : "",
      evidence: isSet(object.evidence) ? globalThis.String(object.evidence) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: Complaint): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.trackingId !== "") {
      obj.trackingId = message.trackingId;
    }
    if (message.anonymousIdentifier !== "") {
      obj.anonymousIdentifier = message.anonymousIdentifier;
    }
    if (message.complaintType !== "") {
      obj.complaintType = message.complaintType;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.area !== "") {
      obj.area = message.area;
    }
    if (message.directedTo !== "") {
      obj.directedTo = message.directedTo;
    }
    if (message.incidentDate !== "") {
      obj.incidentDate = message.incidentDate;
    }
    if (message.evidence !== "") {
      obj.evidence = message.evidence;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Complaint>, I>>(base?: I): Complaint {
    return Complaint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Complaint>, I>>(object: I): Complaint {
    const message = createBaseComplaint();
    message.id = object.id ?? 0;
    message.trackingId = object.trackingId ?? "";
    message.anonymousIdentifier = object.anonymousIdentifier ?? "";
    message.complaintType = object.complaintType ?? "";
    message.title = object.title ?? "";
    message.text = object.text ?? "";
    message.category = object.category ?? "";
    message.area = object.area ?? "";
    message.directedTo = object.directedTo ?? "";
    message.incidentDate = object.incidentDate ?? "";
    message.evidence = object.evidence ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
