// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: sawtak/sawtak/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Complaint } from "./complaint";
import { Params } from "./params";

export const protobufPackage = "sawtak.sawtak.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetComplaintRequest defines the QueryGetComplaintRequest message. */
export interface QueryGetComplaintRequest {
  id: number;
}

/** QueryGetComplaintResponse defines the QueryGetComplaintResponse message. */
export interface QueryGetComplaintResponse {
  complaint: Complaint | undefined;
}

/** QueryAllComplaintRequest defines the QueryAllComplaintRequest message. */
export interface QueryAllComplaintRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllComplaintResponse defines the QueryAllComplaintResponse message. */
export interface QueryAllComplaintResponse {
  complaint: Complaint[];
  pagination: PageResponse | undefined;
}

/** QueryFilterComplaintsRequest defines the QueryFilterComplaintsRequest message. */
export interface QueryFilterComplaintsRequest {
  status: string;
  area: string;
  category: string;
}

/** QueryFilterComplaintsResponse defines the QueryFilterComplaintsResponse message. */
export interface QueryFilterComplaintsResponse {
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetComplaintRequest(): QueryGetComplaintRequest {
  return { id: 0 };
}

export const QueryGetComplaintRequest: MessageFns<QueryGetComplaintRequest> = {
  encode(message: QueryGetComplaintRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetComplaintRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetComplaintRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetComplaintRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetComplaintRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetComplaintRequest>, I>>(base?: I): QueryGetComplaintRequest {
    return QueryGetComplaintRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetComplaintRequest>, I>>(object: I): QueryGetComplaintRequest {
    const message = createBaseQueryGetComplaintRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetComplaintResponse(): QueryGetComplaintResponse {
  return { complaint: undefined };
}

export const QueryGetComplaintResponse: MessageFns<QueryGetComplaintResponse> = {
  encode(message: QueryGetComplaintResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.complaint !== undefined) {
      Complaint.encode(message.complaint, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetComplaintResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetComplaintResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.complaint = Complaint.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetComplaintResponse {
    return { complaint: isSet(object.complaint) ? Complaint.fromJSON(object.complaint) : undefined };
  },

  toJSON(message: QueryGetComplaintResponse): unknown {
    const obj: any = {};
    if (message.complaint !== undefined) {
      obj.complaint = Complaint.toJSON(message.complaint);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetComplaintResponse>, I>>(base?: I): QueryGetComplaintResponse {
    return QueryGetComplaintResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetComplaintResponse>, I>>(object: I): QueryGetComplaintResponse {
    const message = createBaseQueryGetComplaintResponse();
    message.complaint = (object.complaint !== undefined && object.complaint !== null)
      ? Complaint.fromPartial(object.complaint)
      : undefined;
    return message;
  },
};

function createBaseQueryAllComplaintRequest(): QueryAllComplaintRequest {
  return { pagination: undefined };
}

export const QueryAllComplaintRequest: MessageFns<QueryAllComplaintRequest> = {
  encode(message: QueryAllComplaintRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllComplaintRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllComplaintRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllComplaintRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllComplaintRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllComplaintRequest>, I>>(base?: I): QueryAllComplaintRequest {
    return QueryAllComplaintRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllComplaintRequest>, I>>(object: I): QueryAllComplaintRequest {
    const message = createBaseQueryAllComplaintRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllComplaintResponse(): QueryAllComplaintResponse {
  return { complaint: [], pagination: undefined };
}

export const QueryAllComplaintResponse: MessageFns<QueryAllComplaintResponse> = {
  encode(message: QueryAllComplaintResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.complaint) {
      Complaint.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllComplaintResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllComplaintResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.complaint.push(Complaint.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllComplaintResponse {
    return {
      complaint: globalThis.Array.isArray(object?.complaint)
        ? object.complaint.map((e: any) => Complaint.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllComplaintResponse): unknown {
    const obj: any = {};
    if (message.complaint?.length) {
      obj.complaint = message.complaint.map((e) => Complaint.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllComplaintResponse>, I>>(base?: I): QueryAllComplaintResponse {
    return QueryAllComplaintResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllComplaintResponse>, I>>(object: I): QueryAllComplaintResponse {
    const message = createBaseQueryAllComplaintResponse();
    message.complaint = object.complaint?.map((e) => Complaint.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryFilterComplaintsRequest(): QueryFilterComplaintsRequest {
  return { status: "", area: "", category: "" };
}

export const QueryFilterComplaintsRequest: MessageFns<QueryFilterComplaintsRequest> = {
  encode(message: QueryFilterComplaintsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.area !== "") {
      writer.uint32(18).string(message.area);
    }
    if (message.category !== "") {
      writer.uint32(26).string(message.category);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFilterComplaintsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFilterComplaintsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.area = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.category = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFilterComplaintsRequest {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      area: isSet(object.area) ? globalThis.String(object.area) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
    };
  },

  toJSON(message: QueryFilterComplaintsRequest): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.area !== "") {
      obj.area = message.area;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFilterComplaintsRequest>, I>>(base?: I): QueryFilterComplaintsRequest {
    return QueryFilterComplaintsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFilterComplaintsRequest>, I>>(object: I): QueryFilterComplaintsRequest {
    const message = createBaseQueryFilterComplaintsRequest();
    message.status = object.status ?? "";
    message.area = object.area ?? "";
    message.category = object.category ?? "";
    return message;
  },
};

function createBaseQueryFilterComplaintsResponse(): QueryFilterComplaintsResponse {
  return {};
}

export const QueryFilterComplaintsResponse: MessageFns<QueryFilterComplaintsResponse> = {
  encode(_: QueryFilterComplaintsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFilterComplaintsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFilterComplaintsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryFilterComplaintsResponse {
    return {};
  },

  toJSON(_: QueryFilterComplaintsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFilterComplaintsResponse>, I>>(base?: I): QueryFilterComplaintsResponse {
    return QueryFilterComplaintsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFilterComplaintsResponse>, I>>(_: I): QueryFilterComplaintsResponse {
    const message = createBaseQueryFilterComplaintsResponse();
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** ListComplaint Queries a list of Complaint items. */
  GetComplaint(request: QueryGetComplaintRequest): Promise<QueryGetComplaintResponse>;
  /** ListComplaint defines the ListComplaint RPC. */
  ListComplaint(request: QueryAllComplaintRequest): Promise<QueryAllComplaintResponse>;
  /** FilterComplaints Queries a list of FilterComplaints items. */
  FilterComplaints(request: QueryFilterComplaintsRequest): Promise<QueryFilterComplaintsResponse>;
}

export const QueryServiceName = "sawtak.sawtak.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetComplaint = this.GetComplaint.bind(this);
    this.ListComplaint = this.ListComplaint.bind(this);
    this.FilterComplaints = this.FilterComplaints.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  GetComplaint(request: QueryGetComplaintRequest): Promise<QueryGetComplaintResponse> {
    const data = QueryGetComplaintRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetComplaint", data);
    return promise.then((data) => QueryGetComplaintResponse.decode(new BinaryReader(data)));
  }

  ListComplaint(request: QueryAllComplaintRequest): Promise<QueryAllComplaintResponse> {
    const data = QueryAllComplaintRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListComplaint", data);
    return promise.then((data) => QueryAllComplaintResponse.decode(new BinaryReader(data)));
  }

  FilterComplaints(request: QueryFilterComplaintsRequest): Promise<QueryFilterComplaintsResponse> {
    const data = QueryFilterComplaintsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FilterComplaints", data);
    return promise.then((data) => QueryFilterComplaintsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
