// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: sawtak/sawtak/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "sawtak.sawtak.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgSubmitIdentifiedComplaint defines the MsgSubmitIdentifiedComplaint message. */
export interface MsgSubmitIdentifiedComplaint {
  creator: string;
  trackingId: string;
  title: string;
  text: string;
  category: string;
  area: string;
  directedTo: string;
  incidentDate: string;
  evidence: string;
}

/** MsgSubmitIdentifiedComplaintResponse defines the MsgSubmitIdentifiedComplaintResponse message. */
export interface MsgSubmitIdentifiedComplaintResponse {
}

/** MsgSubmitAnonymousComplaint defines the MsgSubmitAnonymousComplaint message. */
export interface MsgSubmitAnonymousComplaint {
  creator: string;
  trackingId: string;
  anonymousIdentifier: string;
  title: string;
  text: string;
  category: string;
  area: string;
  directedTo: string;
  incidentDate: string;
  evidence: string;
  proof: string;
}

/** MsgSubmitAnonymousComplaintResponse defines the MsgSubmitAnonymousComplaintResponse message. */
export interface MsgSubmitAnonymousComplaintResponse {
}

/** MsgUpdateComplaintStatus defines the MsgUpdateComplaintStatus message. */
export interface MsgUpdateComplaintStatus {
  creator: string;
  complaintId: string;
  oldStatus: string;
  newStatus: string;
  publicNotes: string;
}

/** MsgUpdateComplaintStatusResponse defines the MsgUpdateComplaintStatusResponse message. */
export interface MsgUpdateComplaintStatusResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgSubmitIdentifiedComplaint(): MsgSubmitIdentifiedComplaint {
  return {
    creator: "",
    trackingId: "",
    title: "",
    text: "",
    category: "",
    area: "",
    directedTo: "",
    incidentDate: "",
    evidence: "",
  };
}

export const MsgSubmitIdentifiedComplaint: MessageFns<MsgSubmitIdentifiedComplaint> = {
  encode(message: MsgSubmitIdentifiedComplaint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.trackingId !== "") {
      writer.uint32(18).string(message.trackingId);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.text !== "") {
      writer.uint32(34).string(message.text);
    }
    if (message.category !== "") {
      writer.uint32(42).string(message.category);
    }
    if (message.area !== "") {
      writer.uint32(50).string(message.area);
    }
    if (message.directedTo !== "") {
      writer.uint32(58).string(message.directedTo);
    }
    if (message.incidentDate !== "") {
      writer.uint32(66).string(message.incidentDate);
    }
    if (message.evidence !== "") {
      writer.uint32(74).string(message.evidence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitIdentifiedComplaint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitIdentifiedComplaint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.trackingId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.area = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.directedTo = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.incidentDate = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.evidence = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitIdentifiedComplaint {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      trackingId: isSet(object.trackingId)
        ? globalThis.String(object.trackingId)
        : isSet(object.tracking_id)
        ? globalThis.String(object.tracking_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      area: isSet(object.area) ? globalThis.String(object.area) : "",
      directedTo: isSet(object.directedTo)
        ? globalThis.String(object.directedTo)
        : isSet(object.directed_to)
        ? globalThis.String(object.directed_to)
        : "",
      incidentDate: isSet(object.incidentDate)
        ? globalThis.String(object.incidentDate)
        : isSet(object.incident_date)
        ? globalThis.String(object.incident_date)
        : "",
      evidence: isSet(object.evidence) ? globalThis.String(object.evidence) : "",
    };
  },

  toJSON(message: MsgSubmitIdentifiedComplaint): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.trackingId !== "") {
      obj.trackingId = message.trackingId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.area !== "") {
      obj.area = message.area;
    }
    if (message.directedTo !== "") {
      obj.directedTo = message.directedTo;
    }
    if (message.incidentDate !== "") {
      obj.incidentDate = message.incidentDate;
    }
    if (message.evidence !== "") {
      obj.evidence = message.evidence;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitIdentifiedComplaint>, I>>(base?: I): MsgSubmitIdentifiedComplaint {
    return MsgSubmitIdentifiedComplaint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitIdentifiedComplaint>, I>>(object: I): MsgSubmitIdentifiedComplaint {
    const message = createBaseMsgSubmitIdentifiedComplaint();
    message.creator = object.creator ?? "";
    message.trackingId = object.trackingId ?? "";
    message.title = object.title ?? "";
    message.text = object.text ?? "";
    message.category = object.category ?? "";
    message.area = object.area ?? "";
    message.directedTo = object.directedTo ?? "";
    message.incidentDate = object.incidentDate ?? "";
    message.evidence = object.evidence ?? "";
    return message;
  },
};

function createBaseMsgSubmitIdentifiedComplaintResponse(): MsgSubmitIdentifiedComplaintResponse {
  return {};
}

export const MsgSubmitIdentifiedComplaintResponse: MessageFns<MsgSubmitIdentifiedComplaintResponse> = {
  encode(_: MsgSubmitIdentifiedComplaintResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitIdentifiedComplaintResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitIdentifiedComplaintResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitIdentifiedComplaintResponse {
    return {};
  },

  toJSON(_: MsgSubmitIdentifiedComplaintResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitIdentifiedComplaintResponse>, I>>(
    base?: I,
  ): MsgSubmitIdentifiedComplaintResponse {
    return MsgSubmitIdentifiedComplaintResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitIdentifiedComplaintResponse>, I>>(
    _: I,
  ): MsgSubmitIdentifiedComplaintResponse {
    const message = createBaseMsgSubmitIdentifiedComplaintResponse();
    return message;
  },
};

function createBaseMsgSubmitAnonymousComplaint(): MsgSubmitAnonymousComplaint {
  return {
    creator: "",
    trackingId: "",
    anonymousIdentifier: "",
    title: "",
    text: "",
    category: "",
    area: "",
    directedTo: "",
    incidentDate: "",
    evidence: "",
    proof: "",
  };
}

export const MsgSubmitAnonymousComplaint: MessageFns<MsgSubmitAnonymousComplaint> = {
  encode(message: MsgSubmitAnonymousComplaint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.trackingId !== "") {
      writer.uint32(18).string(message.trackingId);
    }
    if (message.anonymousIdentifier !== "") {
      writer.uint32(26).string(message.anonymousIdentifier);
    }
    if (message.title !== "") {
      writer.uint32(34).string(message.title);
    }
    if (message.text !== "") {
      writer.uint32(42).string(message.text);
    }
    if (message.category !== "") {
      writer.uint32(50).string(message.category);
    }
    if (message.area !== "") {
      writer.uint32(58).string(message.area);
    }
    if (message.directedTo !== "") {
      writer.uint32(66).string(message.directedTo);
    }
    if (message.incidentDate !== "") {
      writer.uint32(74).string(message.incidentDate);
    }
    if (message.evidence !== "") {
      writer.uint32(82).string(message.evidence);
    }
    if (message.proof !== "") {
      writer.uint32(90).string(message.proof);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitAnonymousComplaint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitAnonymousComplaint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.trackingId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.anonymousIdentifier = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.area = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.directedTo = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.incidentDate = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.evidence = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.proof = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitAnonymousComplaint {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      trackingId: isSet(object.trackingId)
        ? globalThis.String(object.trackingId)
        : isSet(object.tracking_id)
        ? globalThis.String(object.tracking_id)
        : "",
      anonymousIdentifier: isSet(object.anonymousIdentifier)
        ? globalThis.String(object.anonymousIdentifier)
        : isSet(object.anonymous_identifier)
        ? globalThis.String(object.anonymous_identifier)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      area: isSet(object.area) ? globalThis.String(object.area) : "",
      directedTo: isSet(object.directedTo)
        ? globalThis.String(object.directedTo)
        : isSet(object.directed_to)
        ? globalThis.String(object.directed_to)
        : "",
      incidentDate: isSet(object.incidentDate)
        ? globalThis.String(object.incidentDate)
        : isSet(object.incident_date)
        ? globalThis.String(object.incident_date)
        : "",
      evidence: isSet(object.evidence) ? globalThis.String(object.evidence) : "",
      proof: isSet(object.proof) ? globalThis.String(object.proof) : "",
    };
  },

  toJSON(message: MsgSubmitAnonymousComplaint): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.trackingId !== "") {
      obj.trackingId = message.trackingId;
    }
    if (message.anonymousIdentifier !== "") {
      obj.anonymousIdentifier = message.anonymousIdentifier;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.area !== "") {
      obj.area = message.area;
    }
    if (message.directedTo !== "") {
      obj.directedTo = message.directedTo;
    }
    if (message.incidentDate !== "") {
      obj.incidentDate = message.incidentDate;
    }
    if (message.evidence !== "") {
      obj.evidence = message.evidence;
    }
    if (message.proof !== "") {
      obj.proof = message.proof;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitAnonymousComplaint>, I>>(base?: I): MsgSubmitAnonymousComplaint {
    return MsgSubmitAnonymousComplaint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitAnonymousComplaint>, I>>(object: I): MsgSubmitAnonymousComplaint {
    const message = createBaseMsgSubmitAnonymousComplaint();
    message.creator = object.creator ?? "";
    message.trackingId = object.trackingId ?? "";
    message.anonymousIdentifier = object.anonymousIdentifier ?? "";
    message.title = object.title ?? "";
    message.text = object.text ?? "";
    message.category = object.category ?? "";
    message.area = object.area ?? "";
    message.directedTo = object.directedTo ?? "";
    message.incidentDate = object.incidentDate ?? "";
    message.evidence = object.evidence ?? "";
    message.proof = object.proof ?? "";
    return message;
  },
};

function createBaseMsgSubmitAnonymousComplaintResponse(): MsgSubmitAnonymousComplaintResponse {
  return {};
}

export const MsgSubmitAnonymousComplaintResponse: MessageFns<MsgSubmitAnonymousComplaintResponse> = {
  encode(_: MsgSubmitAnonymousComplaintResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitAnonymousComplaintResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitAnonymousComplaintResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitAnonymousComplaintResponse {
    return {};
  },

  toJSON(_: MsgSubmitAnonymousComplaintResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitAnonymousComplaintResponse>, I>>(
    base?: I,
  ): MsgSubmitAnonymousComplaintResponse {
    return MsgSubmitAnonymousComplaintResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitAnonymousComplaintResponse>, I>>(
    _: I,
  ): MsgSubmitAnonymousComplaintResponse {
    const message = createBaseMsgSubmitAnonymousComplaintResponse();
    return message;
  },
};

function createBaseMsgUpdateComplaintStatus(): MsgUpdateComplaintStatus {
  return { creator: "", complaintId: "", oldStatus: "", newStatus: "", publicNotes: "" };
}

export const MsgUpdateComplaintStatus: MessageFns<MsgUpdateComplaintStatus> = {
  encode(message: MsgUpdateComplaintStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.complaintId !== "") {
      writer.uint32(18).string(message.complaintId);
    }
    if (message.oldStatus !== "") {
      writer.uint32(26).string(message.oldStatus);
    }
    if (message.newStatus !== "") {
      writer.uint32(34).string(message.newStatus);
    }
    if (message.publicNotes !== "") {
      writer.uint32(42).string(message.publicNotes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateComplaintStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateComplaintStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.complaintId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.oldStatus = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.newStatus = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.publicNotes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateComplaintStatus {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      complaintId: isSet(object.complaintId)
        ? globalThis.String(object.complaintId)
        : isSet(object.complaint_id)
        ? globalThis.String(object.complaint_id)
        : "",
      oldStatus: isSet(object.oldStatus)
        ? globalThis.String(object.oldStatus)
        : isSet(object.old_status)
        ? globalThis.String(object.old_status)
        : "",
      newStatus: isSet(object.newStatus)
        ? globalThis.String(object.newStatus)
        : isSet(object.new_status)
        ? globalThis.String(object.new_status)
        : "",
      publicNotes: isSet(object.publicNotes)
        ? globalThis.String(object.publicNotes)
        : isSet(object.public_notes)
        ? globalThis.String(object.public_notes)
        : "",
    };
  },

  toJSON(message: MsgUpdateComplaintStatus): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.complaintId !== "") {
      obj.complaintId = message.complaintId;
    }
    if (message.oldStatus !== "") {
      obj.oldStatus = message.oldStatus;
    }
    if (message.newStatus !== "") {
      obj.newStatus = message.newStatus;
    }
    if (message.publicNotes !== "") {
      obj.publicNotes = message.publicNotes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateComplaintStatus>, I>>(base?: I): MsgUpdateComplaintStatus {
    return MsgUpdateComplaintStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateComplaintStatus>, I>>(object: I): MsgUpdateComplaintStatus {
    const message = createBaseMsgUpdateComplaintStatus();
    message.creator = object.creator ?? "";
    message.complaintId = object.complaintId ?? "";
    message.oldStatus = object.oldStatus ?? "";
    message.newStatus = object.newStatus ?? "";
    message.publicNotes = object.publicNotes ?? "";
    return message;
  },
};

function createBaseMsgUpdateComplaintStatusResponse(): MsgUpdateComplaintStatusResponse {
  return {};
}

export const MsgUpdateComplaintStatusResponse: MessageFns<MsgUpdateComplaintStatusResponse> = {
  encode(_: MsgUpdateComplaintStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateComplaintStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateComplaintStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateComplaintStatusResponse {
    return {};
  },

  toJSON(_: MsgUpdateComplaintStatusResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateComplaintStatusResponse>, I>>(
    base?: I,
  ): MsgUpdateComplaintStatusResponse {
    return MsgUpdateComplaintStatusResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateComplaintStatusResponse>, I>>(
    _: I,
  ): MsgUpdateComplaintStatusResponse {
    const message = createBaseMsgUpdateComplaintStatusResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** SubmitIdentifiedComplaint defines the SubmitIdentifiedComplaint RPC. */
  SubmitIdentifiedComplaint(request: MsgSubmitIdentifiedComplaint): Promise<MsgSubmitIdentifiedComplaintResponse>;
  /** SubmitAnonymousComplaint defines the SubmitAnonymousComplaint RPC. */
  SubmitAnonymousComplaint(request: MsgSubmitAnonymousComplaint): Promise<MsgSubmitAnonymousComplaintResponse>;
  /** UpdateComplaintStatus defines the UpdateComplaintStatus RPC. */
  UpdateComplaintStatus(request: MsgUpdateComplaintStatus): Promise<MsgUpdateComplaintStatusResponse>;
}

export const MsgServiceName = "sawtak.sawtak.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.SubmitIdentifiedComplaint = this.SubmitIdentifiedComplaint.bind(this);
    this.SubmitAnonymousComplaint = this.SubmitAnonymousComplaint.bind(this);
    this.UpdateComplaintStatus = this.UpdateComplaintStatus.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  SubmitIdentifiedComplaint(request: MsgSubmitIdentifiedComplaint): Promise<MsgSubmitIdentifiedComplaintResponse> {
    const data = MsgSubmitIdentifiedComplaint.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitIdentifiedComplaint", data);
    return promise.then((data) => MsgSubmitIdentifiedComplaintResponse.decode(new BinaryReader(data)));
  }

  SubmitAnonymousComplaint(request: MsgSubmitAnonymousComplaint): Promise<MsgSubmitAnonymousComplaintResponse> {
    const data = MsgSubmitAnonymousComplaint.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitAnonymousComplaint", data);
    return promise.then((data) => MsgSubmitAnonymousComplaintResponse.decode(new BinaryReader(data)));
  }

  UpdateComplaintStatus(request: MsgUpdateComplaintStatus): Promise<MsgUpdateComplaintStatusResponse> {
    const data = MsgUpdateComplaintStatus.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateComplaintStatus", data);
    return promise.then((data) => MsgUpdateComplaintStatusResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
