// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sawtak/sawtak/v1/complaint.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Complaint defines the Complaint message.
type Complaint struct {
	Id                  uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackingId          string `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	AnonymousIdentifier string `protobuf:"bytes,3,opt,name=anonymous_identifier,json=anonymousIdentifier,proto3" json:"anonymous_identifier,omitempty"`
	ComplaintType       string `protobuf:"bytes,4,opt,name=complaint_type,json=complaintType,proto3" json:"complaint_type,omitempty"`
	Title               string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Text                string `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Category            string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Area                string `protobuf:"bytes,8,opt,name=area,proto3" json:"area,omitempty"`
	DirectedTo          string `protobuf:"bytes,9,opt,name=directed_to,json=directedTo,proto3" json:"directed_to,omitempty"`
	IncidentDate        string `protobuf:"bytes,10,opt,name=incident_date,json=incidentDate,proto3" json:"incident_date,omitempty"`
	Evidence            string `protobuf:"bytes,11,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Status              string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *Complaint) Reset()         { *m = Complaint{} }
func (m *Complaint) String() string { return proto.CompactTextString(m) }
func (*Complaint) ProtoMessage()    {}
func (*Complaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_a080f8d5b7cd4a29, []int{0}
}
func (m *Complaint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Complaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Complaint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Complaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complaint.Merge(m, src)
}
func (m *Complaint) XXX_Size() int {
	return m.Size()
}
func (m *Complaint) XXX_DiscardUnknown() {
	xxx_messageInfo_Complaint.DiscardUnknown(m)
}

var xxx_messageInfo_Complaint proto.InternalMessageInfo

func (m *Complaint) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Complaint) GetTrackingId() string {
	if m != nil {
		return m.TrackingId
	}
	return ""
}

func (m *Complaint) GetAnonymousIdentifier() string {
	if m != nil {
		return m.AnonymousIdentifier
	}
	return ""
}

func (m *Complaint) GetComplaintType() string {
	if m != nil {
		return m.ComplaintType
	}
	return ""
}

func (m *Complaint) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Complaint) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Complaint) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Complaint) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *Complaint) GetDirectedTo() string {
	if m != nil {
		return m.DirectedTo
	}
	return ""
}

func (m *Complaint) GetIncidentDate() string {
	if m != nil {
		return m.IncidentDate
	}
	return ""
}

func (m *Complaint) GetEvidence() string {
	if m != nil {
		return m.Evidence
	}
	return ""
}

func (m *Complaint) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Complaint)(nil), "sawtak.sawtak.v1.Complaint")
}

func init() { proto.RegisterFile("sawtak/sawtak/v1/complaint.proto", fileDescriptor_a080f8d5b7cd4a29) }

var fileDescriptor_a080f8d5b7cd4a29 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x69, 0x5f, 0xe0, 0x85, 0xe5, 0x4f, 0xcc, 0x4a, 0xcc, 0xc6, 0x43, 0x25, 0x1a, 0x13,
	0x4e, 0x25, 0xc4, 0x6f, 0xa0, 0x1e, 0xe4, 0x28, 0xe1, 0xe4, 0xa5, 0x59, 0xba, 0x23, 0x4c, 0xa0,
	0xdd, 0xa6, 0x1d, 0x90, 0x7e, 0x0b, 0x3f, 0x96, 0x47, 0x8e, 0x1e, 0x0d, 0xdc, 0xfc, 0x14, 0xa6,
	0x5b, 0xb6, 0xa7, 0x99, 0xe7, 0x79, 0x7e, 0xc9, 0xec, 0xec, 0xb0, 0x61, 0x26, 0x3f, 0x48, 0xae,
	0xc7, 0xe7, 0xb2, 0x9b, 0x8c, 0x43, 0x1d, 0x25, 0x1b, 0x89, 0x31, 0xf9, 0x49, 0xaa, 0x49, 0xf3,
	0x8b, 0x32, 0xf2, 0xcf, 0x65, 0x37, 0xb9, 0xfd, 0x75, 0x59, 0xfb, 0xc9, 0x52, 0xbc, 0xcf, 0x5c,
	0x54, 0xc2, 0x19, 0x3a, 0xa3, 0xfa, 0xcc, 0x45, 0xc5, 0x6f, 0x58, 0x87, 0x52, 0x19, 0xae, 0x31,
	0x5e, 0x06, 0xa8, 0x84, 0x3b, 0x74, 0x46, 0xed, 0x19, 0xb3, 0xd6, 0x54, 0xf1, 0x09, 0x1b, 0xc8,
	0x58, 0xc7, 0x79, 0xa4, 0xb7, 0x59, 0x80, 0x0a, 0x62, 0xc2, 0x77, 0x84, 0x54, 0xfc, 0x33, 0xe4,
	0x65, 0x95, 0x4d, 0xab, 0x88, 0xdf, 0xb3, 0x7e, 0xf5, 0xac, 0x80, 0xf2, 0x04, 0x44, 0xdd, 0xc0,
	0xbd, 0xca, 0x9d, 0xe7, 0x09, 0xf0, 0x01, 0x6b, 0x10, 0xd2, 0x06, 0x44, 0xc3, 0xa4, 0xa5, 0xe0,
	0x9c, 0xd5, 0x09, 0xf6, 0x24, 0x9a, 0xc6, 0x34, 0x3d, 0xbf, 0x66, 0xad, 0x50, 0x12, 0x2c, 0x75,
	0x9a, 0x8b, 0xff, 0xc6, 0xaf, 0x74, 0xc1, 0xcb, 0x14, 0xa4, 0x68, 0x95, 0x7c, 0xd1, 0x17, 0x4b,
	0x29, 0x4c, 0x21, 0x24, 0x50, 0x01, 0x69, 0xd1, 0x2e, 0x97, 0xb2, 0xd6, 0x5c, 0xf3, 0x3b, 0xd6,
	0xc3, 0x38, 0x34, 0xdb, 0x04, 0x4a, 0x12, 0x08, 0x66, 0x90, 0xae, 0x35, 0x9f, 0x25, 0x41, 0x31,
	0x15, 0x76, 0x85, 0x0c, 0x41, 0x74, 0xca, 0xa9, 0x56, 0xf3, 0x2b, 0xd6, 0xcc, 0x48, 0xd2, 0x36,
	0x13, 0x5d, 0x93, 0x9c, 0xd5, 0xe3, 0xcb, 0xd7, 0xd1, 0x73, 0x0e, 0x47, 0xcf, 0xf9, 0x39, 0x7a,
	0xce, 0xe7, 0xc9, 0xab, 0x1d, 0x4e, 0x5e, 0xed, 0xfb, 0xe4, 0xd5, 0xde, 0xfc, 0x25, 0xd2, 0x6a,
	0xbb, 0xf0, 0x43, 0x1d, 0x8d, 0x33, 0x99, 0x83, 0xc2, 0x45, 0x2a, 0x57, 0x18, 0xbd, 0xda, 0x63,
	0xee, 0x6d, 0x53, 0xfc, 0x58, 0xb6, 0x68, 0x9a, 0x7b, 0x3e, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x26, 0x7f, 0x98, 0xf3, 0x01, 0x00, 0x00,
}

func (m *Complaint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Complaint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Complaint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Evidence) > 0 {
		i -= len(m.Evidence)
		copy(dAtA[i:], m.Evidence)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.Evidence)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.IncidentDate) > 0 {
		i -= len(m.IncidentDate)
		copy(dAtA[i:], m.IncidentDate)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.IncidentDate)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.DirectedTo) > 0 {
		i -= len(m.DirectedTo)
		copy(dAtA[i:], m.DirectedTo)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.DirectedTo)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Area) > 0 {
		i -= len(m.Area)
		copy(dAtA[i:], m.Area)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.Area)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ComplaintType) > 0 {
		i -= len(m.ComplaintType)
		copy(dAtA[i:], m.ComplaintType)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.ComplaintType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AnonymousIdentifier) > 0 {
		i -= len(m.AnonymousIdentifier)
		copy(dAtA[i:], m.AnonymousIdentifier)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.AnonymousIdentifier)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrackingId) > 0 {
		i -= len(m.TrackingId)
		copy(dAtA[i:], m.TrackingId)
		i = encodeVarintComplaint(dAtA, i, uint64(len(m.TrackingId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintComplaint(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintComplaint(dAtA []byte, offset int, v uint64) int {
	offset -= sovComplaint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Complaint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovComplaint(uint64(m.Id))
	}
	l = len(m.TrackingId)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.AnonymousIdentifier)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.ComplaintType)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.Area)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.DirectedTo)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.IncidentDate)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.Evidence)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovComplaint(uint64(l))
	}
	return n
}

func sovComplaint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozComplaint(x uint64) (n int) {
	return sovComplaint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Complaint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComplaint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Complaint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Complaint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrackingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrackingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnonymousIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnonymousIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComplaintType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ComplaintType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Area", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Area = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DirectedTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DirectedTo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncidentDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncidentDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Evidence = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComplaint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComplaint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipComplaint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthComplaint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipComplaint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowComplaint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowComplaint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthComplaint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupComplaint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthComplaint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthComplaint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowComplaint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupComplaint = fmt.Errorf("proto: unexpected end of group")
)
