// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sawtak/sawtak/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetComplaintRequest defines the QueryGetComplaintRequest message.
type QueryGetComplaintRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetComplaintRequest) Reset()         { *m = QueryGetComplaintRequest{} }
func (m *QueryGetComplaintRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetComplaintRequest) ProtoMessage()    {}
func (*QueryGetComplaintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{2}
}
func (m *QueryGetComplaintRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetComplaintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetComplaintRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetComplaintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetComplaintRequest.Merge(m, src)
}
func (m *QueryGetComplaintRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetComplaintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetComplaintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetComplaintRequest proto.InternalMessageInfo

func (m *QueryGetComplaintRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryGetComplaintResponse defines the QueryGetComplaintResponse message.
type QueryGetComplaintResponse struct {
	Complaint Complaint `protobuf:"bytes,1,opt,name=complaint,proto3" json:"complaint"`
}

func (m *QueryGetComplaintResponse) Reset()         { *m = QueryGetComplaintResponse{} }
func (m *QueryGetComplaintResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetComplaintResponse) ProtoMessage()    {}
func (*QueryGetComplaintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{3}
}
func (m *QueryGetComplaintResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetComplaintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetComplaintResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetComplaintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetComplaintResponse.Merge(m, src)
}
func (m *QueryGetComplaintResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetComplaintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetComplaintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetComplaintResponse proto.InternalMessageInfo

func (m *QueryGetComplaintResponse) GetComplaint() Complaint {
	if m != nil {
		return m.Complaint
	}
	return Complaint{}
}

// QueryAllComplaintRequest defines the QueryAllComplaintRequest message.
type QueryAllComplaintRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllComplaintRequest) Reset()         { *m = QueryAllComplaintRequest{} }
func (m *QueryAllComplaintRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllComplaintRequest) ProtoMessage()    {}
func (*QueryAllComplaintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{4}
}
func (m *QueryAllComplaintRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllComplaintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllComplaintRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllComplaintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllComplaintRequest.Merge(m, src)
}
func (m *QueryAllComplaintRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllComplaintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllComplaintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllComplaintRequest proto.InternalMessageInfo

func (m *QueryAllComplaintRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllComplaintResponse defines the QueryAllComplaintResponse message.
type QueryAllComplaintResponse struct {
	Complaint  []Complaint         `protobuf:"bytes,1,rep,name=complaint,proto3" json:"complaint"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllComplaintResponse) Reset()         { *m = QueryAllComplaintResponse{} }
func (m *QueryAllComplaintResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllComplaintResponse) ProtoMessage()    {}
func (*QueryAllComplaintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{5}
}
func (m *QueryAllComplaintResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllComplaintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllComplaintResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllComplaintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllComplaintResponse.Merge(m, src)
}
func (m *QueryAllComplaintResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllComplaintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllComplaintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllComplaintResponse proto.InternalMessageInfo

func (m *QueryAllComplaintResponse) GetComplaint() []Complaint {
	if m != nil {
		return m.Complaint
	}
	return nil
}

func (m *QueryAllComplaintResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryFilterComplaintsRequest defines the QueryFilterComplaintsRequest message.
type QueryFilterComplaintsRequest struct {
	Status   string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Area     string `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (m *QueryFilterComplaintsRequest) Reset()         { *m = QueryFilterComplaintsRequest{} }
func (m *QueryFilterComplaintsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFilterComplaintsRequest) ProtoMessage()    {}
func (*QueryFilterComplaintsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{6}
}
func (m *QueryFilterComplaintsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFilterComplaintsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFilterComplaintsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFilterComplaintsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFilterComplaintsRequest.Merge(m, src)
}
func (m *QueryFilterComplaintsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFilterComplaintsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFilterComplaintsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFilterComplaintsRequest proto.InternalMessageInfo

func (m *QueryFilterComplaintsRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryFilterComplaintsRequest) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *QueryFilterComplaintsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// QueryFilterComplaintsResponse defines the QueryFilterComplaintsResponse message.
type QueryFilterComplaintsResponse struct {
	Complaints []Complaint `protobuf:"bytes,1,rep,name=complaints,proto3" json:"complaints"`
}

func (m *QueryFilterComplaintsResponse) Reset()         { *m = QueryFilterComplaintsResponse{} }
func (m *QueryFilterComplaintsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFilterComplaintsResponse) ProtoMessage()    {}
func (*QueryFilterComplaintsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e64dd868f37a760a, []int{7}
}
func (m *QueryFilterComplaintsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFilterComplaintsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFilterComplaintsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFilterComplaintsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFilterComplaintsResponse.Merge(m, src)
}
func (m *QueryFilterComplaintsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFilterComplaintsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFilterComplaintsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFilterComplaintsResponse proto.InternalMessageInfo

func (m *QueryFilterComplaintsResponse) GetComplaints() []Complaint {
	if m != nil {
		return m.Complaints
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "sawtak.sawtak.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "sawtak.sawtak.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetComplaintRequest)(nil), "sawtak.sawtak.v1.QueryGetComplaintRequest")
	proto.RegisterType((*QueryGetComplaintResponse)(nil), "sawtak.sawtak.v1.QueryGetComplaintResponse")
	proto.RegisterType((*QueryAllComplaintRequest)(nil), "sawtak.sawtak.v1.QueryAllComplaintRequest")
	proto.RegisterType((*QueryAllComplaintResponse)(nil), "sawtak.sawtak.v1.QueryAllComplaintResponse")
	proto.RegisterType((*QueryFilterComplaintsRequest)(nil), "sawtak.sawtak.v1.QueryFilterComplaintsRequest")
	proto.RegisterType((*QueryFilterComplaintsResponse)(nil), "sawtak.sawtak.v1.QueryFilterComplaintsResponse")
}

func init() { proto.RegisterFile("sawtak/sawtak/v1/query.proto", fileDescriptor_e64dd868f37a760a) }

var fileDescriptor_e64dd868f37a760a = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xe3, 0x34, 0x44, 0xe4, 0xf1, 0x43, 0xed, 0xb5, 0xaa, 0x12, 0x27, 0x31, 0xc5, 0xfc,
	0x54, 0x90, 0x7c, 0x4a, 0x19, 0x19, 0x50, 0x83, 0xd4, 0x32, 0x30, 0xb4, 0x1e, 0x11, 0xcb, 0x39,
	0xb9, 0xba, 0x27, 0x62, 0x9f, 0xeb, 0xbb, 0x04, 0x22, 0xc4, 0xc2, 0xc0, 0xc0, 0x84, 0xc4, 0xc2,
	0x3f, 0x80, 0x84, 0x98, 0xf8, 0x33, 0x3a, 0x56, 0x62, 0x61, 0x42, 0x28, 0x41, 0xe2, 0xdf, 0x40,
	0x39, 0x5f, 0xd2, 0xa4, 0x76, 0xd4, 0xb0, 0xc4, 0xe7, 0x97, 0xf7, 0x7d, 0xef, 0xf3, 0x7e, 0x9c,
	0xa1, 0x26, 0xc8, 0x2b, 0x49, 0x5e, 0x62, 0xfd, 0xe8, 0x37, 0xf1, 0x71, 0x8f, 0xc6, 0x03, 0x27,
	0x8a, 0xb9, 0xe4, 0x68, 0x35, 0x31, 0x3b, 0xfa, 0xd1, 0x6f, 0x9a, 0x6b, 0x24, 0x60, 0x21, 0xc7,
	0xea, 0x37, 0x71, 0x32, 0x1b, 0x6d, 0x2e, 0x02, 0x2e, 0xb0, 0x47, 0x04, 0x4d, 0xd4, 0xb8, 0xdf,
	0xf4, 0xa8, 0x24, 0x4d, 0x1c, 0x11, 0x9f, 0x85, 0x44, 0x32, 0x1e, 0x6a, 0xdf, 0x0d, 0x9f, 0xfb,
	0x5c, 0x1d, 0xf1, 0xf8, 0xa4, 0xad, 0x35, 0x9f, 0x73, 0xbf, 0x4b, 0x31, 0x89, 0x18, 0x26, 0x61,
	0xc8, 0xa5, 0x92, 0x08, 0xfd, 0xef, 0x56, 0x0a, 0xb1, 0xcd, 0x83, 0xa8, 0x4b, 0x58, 0x28, 0xb5,
	0x47, 0x3d, 0xe5, 0x11, 0x91, 0x98, 0x04, 0x3a, 0x80, 0xbd, 0x01, 0xe8, 0x60, 0x8c, 0xb5, 0xaf,
	0x8c, 0x2e, 0x3d, 0xee, 0x51, 0x21, 0x6d, 0x17, 0xd6, 0xe7, 0xac, 0x22, 0xe2, 0xa1, 0xa0, 0xe8,
	0x11, 0x14, 0x13, 0x71, 0xd9, 0xd8, 0x32, 0xee, 0x5f, 0xd9, 0x2e, 0x3b, 0xe7, 0x7b, 0xe0, 0x24,
	0x8a, 0x56, 0xe9, 0xe4, 0xd7, 0x8d, 0xdc, 0xd7, 0xbf, 0xdf, 0x1b, 0x86, 0xab, 0x25, 0x76, 0x03,
	0xca, 0x2a, 0xe6, 0x1e, 0x95, 0x4f, 0x26, 0x8c, 0x3a, 0x1f, 0xba, 0x0e, 0x79, 0xd6, 0x51, 0x41,
	0x0b, 0x6e, 0x9e, 0x75, 0xec, 0x17, 0x50, 0xc9, 0xf0, 0xd5, 0x14, 0x8f, 0xa1, 0x34, 0x2d, 0x52,
	0x83, 0x54, 0xd3, 0x20, 0x53, 0x5d, 0xab, 0x30, 0x66, 0x71, 0xcf, 0x34, 0xb6, 0xa7, 0x49, 0x76,
	0xba, 0xdd, 0x14, 0xc9, 0x2e, 0xc0, 0xd9, 0x60, 0x74, 0xf4, 0xbb, 0x4e, 0x32, 0x45, 0x67, 0x3c,
	0x45, 0x27, 0xd9, 0x01, 0x3d, 0x45, 0x67, 0x9f, 0xf8, 0x54, 0x6b, 0xdd, 0x19, 0xa5, 0xfd, 0xc5,
	0xd0, 0x25, 0xcc, 0x27, 0xc9, 0x2e, 0x61, 0xe5, 0x7f, 0x4b, 0x40, 0x7b, 0x73, 0x98, 0x79, 0x85,
	0x79, 0xef, 0x42, 0xcc, 0x24, 0xfb, 0x1c, 0xe7, 0x21, 0xd4, 0x14, 0xe6, 0x2e, 0xeb, 0x4a, 0x1a,
	0x4f, 0x33, 0x4e, 0x36, 0x01, 0x6d, 0x42, 0x51, 0x48, 0x22, 0x7b, 0xc9, 0xc8, 0x4b, 0xae, 0x7e,
	0x43, 0x08, 0x0a, 0x24, 0xa6, 0x44, 0xa5, 0x2e, 0xb9, 0xea, 0x8c, 0x4c, 0xb8, 0xdc, 0x26, 0x92,
	0xfa, 0x3c, 0x1e, 0x94, 0x57, 0x94, 0x7d, 0xfa, 0x6e, 0x7b, 0x50, 0x5f, 0x90, 0x47, 0xb7, 0x64,
	0x07, 0x60, 0x5a, 0x9e, 0x58, 0xbe, 0x27, 0x33, 0xa2, 0xed, 0x6f, 0x05, 0xb8, 0xa4, 0x92, 0xa0,
	0x08, 0x8a, 0xc9, 0x22, 0xa2, 0xdb, 0xe9, 0x10, 0xe9, 0x7d, 0x37, 0xef, 0x5c, 0xe0, 0x95, 0x30,
	0xda, 0x95, 0x77, 0x3f, 0xfe, 0x7c, 0xca, 0xaf, 0xa3, 0xb5, 0xd4, 0x6d, 0x42, 0x1f, 0x0c, 0xb8,
	0x3a, 0xbb, 0xad, 0xa8, 0xb1, 0x20, 0x64, 0xc6, 0xfa, 0x9b, 0x0f, 0x96, 0xf2, 0xd5, 0x10, 0x37,
	0x15, 0x44, 0x15, 0x55, 0xb2, 0x2e, 0x3d, 0x7e, 0xc3, 0x3a, 0x6f, 0xd1, 0x7b, 0x03, 0xae, 0x3d,
	0x63, 0x62, 0x09, 0x9a, 0x8c, 0x2b, 0xb0, 0x90, 0x26, 0x6b, 0x93, 0xed, 0x9a, 0xa2, 0xd9, 0x44,
	0x1b, 0x59, 0x34, 0xe8, 0xb3, 0x01, 0xab, 0xe7, 0x27, 0x8e, 0x9c, 0x05, 0xf1, 0x17, 0xac, 0xa0,
	0x89, 0x97, 0xf6, 0xd7, 0x4c, 0xb7, 0x14, 0x53, 0x1d, 0x55, 0x33, 0x3b, 0x74, 0xa8, 0x64, 0xad,
	0xa7, 0x27, 0x43, 0xcb, 0x38, 0x1d, 0x5a, 0xc6, 0xef, 0xa1, 0x65, 0x7c, 0x1c, 0x59, 0xb9, 0xd3,
	0x91, 0x95, 0xfb, 0x39, 0xb2, 0x72, 0xcf, 0x1d, 0x9f, 0xc9, 0xa3, 0x9e, 0xe7, 0xb4, 0x79, 0x80,
	0x05, 0x19, 0xd0, 0x0e, 0xf3, 0x62, 0x72, 0xc4, 0x82, 0x83, 0x49, 0xb8, 0xd7, 0x93, 0x83, 0x1c,
	0x44, 0x54, 0x78, 0x45, 0xf5, 0x25, 0x7d, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x74, 0x63, 0x69,
	0xb5, 0x2f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListComplaint Queries a list of Complaint items.
	GetComplaint(ctx context.Context, in *QueryGetComplaintRequest, opts ...grpc.CallOption) (*QueryGetComplaintResponse, error)
	// ListComplaint defines the ListComplaint RPC.
	ListComplaint(ctx context.Context, in *QueryAllComplaintRequest, opts ...grpc.CallOption) (*QueryAllComplaintResponse, error)
	// FilterComplaints queries complaints filtered by status, area, and/or category.
	FilterComplaints(ctx context.Context, in *QueryFilterComplaintsRequest, opts ...grpc.CallOption) (*QueryFilterComplaintsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetComplaint(ctx context.Context, in *QueryGetComplaintRequest, opts ...grpc.CallOption) (*QueryGetComplaintResponse, error) {
	out := new(QueryGetComplaintResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Query/GetComplaint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListComplaint(ctx context.Context, in *QueryAllComplaintRequest, opts ...grpc.CallOption) (*QueryAllComplaintResponse, error) {
	out := new(QueryAllComplaintResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Query/ListComplaint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FilterComplaints(ctx context.Context, in *QueryFilterComplaintsRequest, opts ...grpc.CallOption) (*QueryFilterComplaintsResponse, error) {
	out := new(QueryFilterComplaintsResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Query/FilterComplaints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListComplaint Queries a list of Complaint items.
	GetComplaint(context.Context, *QueryGetComplaintRequest) (*QueryGetComplaintResponse, error)
	// ListComplaint defines the ListComplaint RPC.
	ListComplaint(context.Context, *QueryAllComplaintRequest) (*QueryAllComplaintResponse, error)
	// FilterComplaints queries complaints filtered by status, area, and/or category.
	FilterComplaints(context.Context, *QueryFilterComplaintsRequest) (*QueryFilterComplaintsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetComplaint(ctx context.Context, req *QueryGetComplaintRequest) (*QueryGetComplaintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComplaint not implemented")
}
func (*UnimplementedQueryServer) ListComplaint(ctx context.Context, req *QueryAllComplaintRequest) (*QueryAllComplaintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComplaint not implemented")
}
func (*UnimplementedQueryServer) FilterComplaints(ctx context.Context, req *QueryFilterComplaintsRequest) (*QueryFilterComplaintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterComplaints not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetComplaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Query/GetComplaint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetComplaint(ctx, req.(*QueryGetComplaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllComplaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Query/ListComplaint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListComplaint(ctx, req.(*QueryAllComplaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FilterComplaints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFilterComplaintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FilterComplaints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Query/FilterComplaints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FilterComplaints(ctx, req.(*QueryFilterComplaintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sawtak.sawtak.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetComplaint",
			Handler:    _Query_GetComplaint_Handler,
		},
		{
			MethodName: "ListComplaint",
			Handler:    _Query_ListComplaint_Handler,
		},
		{
			MethodName: "FilterComplaints",
			Handler:    _Query_FilterComplaints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sawtak/sawtak/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetComplaintRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetComplaintRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetComplaintRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetComplaintResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetComplaintResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetComplaintResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Complaint.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllComplaintRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllComplaintRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllComplaintRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllComplaintResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllComplaintResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllComplaintResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Complaint) > 0 {
		for iNdEx := len(m.Complaint) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Complaint[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFilterComplaintsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFilterComplaintsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFilterComplaintsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Area) > 0 {
		i -= len(m.Area)
		copy(dAtA[i:], m.Area)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Area)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFilterComplaintsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFilterComplaintsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFilterComplaintsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Complaints) > 0 {
		for iNdEx := len(m.Complaints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Complaints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetComplaintRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetComplaintResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Complaint.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllComplaintRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllComplaintResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Complaint) > 0 {
		for _, e := range m.Complaint {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFilterComplaintsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Area)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFilterComplaintsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Complaints) > 0 {
		for _, e := range m.Complaints {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetComplaintRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetComplaintRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetComplaintRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetComplaintResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetComplaintResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetComplaintResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Complaint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Complaint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllComplaintRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllComplaintRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllComplaintRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllComplaintResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllComplaintResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllComplaintResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Complaint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Complaint = append(m.Complaint, Complaint{})
			if err := m.Complaint[len(m.Complaint)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFilterComplaintsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFilterComplaintsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFilterComplaintsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Area", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Area = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFilterComplaintsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFilterComplaintsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFilterComplaintsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Complaints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Complaints = append(m.Complaints, Complaint{})
			if err := m.Complaints[len(m.Complaints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
