// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sawtak/sawtak/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgSubmitIdentifiedComplaint defines the MsgSubmitIdentifiedComplaint message.
type MsgSubmitIdentifiedComplaint struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TrackingId   string `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Title        string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text         string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Category     string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Area         string `protobuf:"bytes,6,opt,name=area,proto3" json:"area,omitempty"`
	DirectedTo   string `protobuf:"bytes,7,opt,name=directed_to,json=directedTo,proto3" json:"directed_to,omitempty"`
	IncidentDate string `protobuf:"bytes,8,opt,name=incident_date,json=incidentDate,proto3" json:"incident_date,omitempty"`
	Evidence     string `protobuf:"bytes,9,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

func (m *MsgSubmitIdentifiedComplaint) Reset()         { *m = MsgSubmitIdentifiedComplaint{} }
func (m *MsgSubmitIdentifiedComplaint) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitIdentifiedComplaint) ProtoMessage()    {}
func (*MsgSubmitIdentifiedComplaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{2}
}
func (m *MsgSubmitIdentifiedComplaint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitIdentifiedComplaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitIdentifiedComplaint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitIdentifiedComplaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitIdentifiedComplaint.Merge(m, src)
}
func (m *MsgSubmitIdentifiedComplaint) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitIdentifiedComplaint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitIdentifiedComplaint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitIdentifiedComplaint proto.InternalMessageInfo

func (m *MsgSubmitIdentifiedComplaint) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetTrackingId() string {
	if m != nil {
		return m.TrackingId
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetDirectedTo() string {
	if m != nil {
		return m.DirectedTo
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetIncidentDate() string {
	if m != nil {
		return m.IncidentDate
	}
	return ""
}

func (m *MsgSubmitIdentifiedComplaint) GetEvidence() string {
	if m != nil {
		return m.Evidence
	}
	return ""
}

// MsgSubmitIdentifiedComplaintResponse defines the MsgSubmitIdentifiedComplaintResponse message.
type MsgSubmitIdentifiedComplaintResponse struct {
}

func (m *MsgSubmitIdentifiedComplaintResponse) Reset()         { *m = MsgSubmitIdentifiedComplaintResponse{} }
func (m *MsgSubmitIdentifiedComplaintResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitIdentifiedComplaintResponse) ProtoMessage()    {}
func (*MsgSubmitIdentifiedComplaintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{3}
}
func (m *MsgSubmitIdentifiedComplaintResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitIdentifiedComplaintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitIdentifiedComplaintResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitIdentifiedComplaintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitIdentifiedComplaintResponse.Merge(m, src)
}
func (m *MsgSubmitIdentifiedComplaintResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitIdentifiedComplaintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitIdentifiedComplaintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitIdentifiedComplaintResponse proto.InternalMessageInfo

// MsgSubmitAnonymousComplaint defines the MsgSubmitAnonymousComplaint message.
type MsgSubmitAnonymousComplaint struct {
	Creator             string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AnonymousIdentifier string `protobuf:"bytes,2,opt,name=anonymous_identifier,json=anonymousIdentifier,proto3" json:"anonymous_identifier,omitempty"`
	Title               string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text                string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Category            string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Area                string `protobuf:"bytes,6,opt,name=area,proto3" json:"area,omitempty"`
	DirectedTo          string `protobuf:"bytes,7,opt,name=directed_to,json=directedTo,proto3" json:"directed_to,omitempty"`
	IncidentDate        string `protobuf:"bytes,8,opt,name=incident_date,json=incidentDate,proto3" json:"incident_date,omitempty"`
	Evidence            string `protobuf:"bytes,9,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Proof               string `protobuf:"bytes,10,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *MsgSubmitAnonymousComplaint) Reset()         { *m = MsgSubmitAnonymousComplaint{} }
func (m *MsgSubmitAnonymousComplaint) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitAnonymousComplaint) ProtoMessage()    {}
func (*MsgSubmitAnonymousComplaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{4}
}
func (m *MsgSubmitAnonymousComplaint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitAnonymousComplaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitAnonymousComplaint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitAnonymousComplaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitAnonymousComplaint.Merge(m, src)
}
func (m *MsgSubmitAnonymousComplaint) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitAnonymousComplaint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitAnonymousComplaint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitAnonymousComplaint proto.InternalMessageInfo

func (m *MsgSubmitAnonymousComplaint) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetAnonymousIdentifier() string {
	if m != nil {
		return m.AnonymousIdentifier
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetDirectedTo() string {
	if m != nil {
		return m.DirectedTo
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetIncidentDate() string {
	if m != nil {
		return m.IncidentDate
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetEvidence() string {
	if m != nil {
		return m.Evidence
	}
	return ""
}

func (m *MsgSubmitAnonymousComplaint) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

// MsgSubmitAnonymousComplaintResponse defines the MsgSubmitAnonymousComplaintResponse message.
type MsgSubmitAnonymousComplaintResponse struct {
}

func (m *MsgSubmitAnonymousComplaintResponse) Reset()         { *m = MsgSubmitAnonymousComplaintResponse{} }
func (m *MsgSubmitAnonymousComplaintResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitAnonymousComplaintResponse) ProtoMessage()    {}
func (*MsgSubmitAnonymousComplaintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{5}
}
func (m *MsgSubmitAnonymousComplaintResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitAnonymousComplaintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitAnonymousComplaintResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitAnonymousComplaintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitAnonymousComplaintResponse.Merge(m, src)
}
func (m *MsgSubmitAnonymousComplaintResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitAnonymousComplaintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitAnonymousComplaintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitAnonymousComplaintResponse proto.InternalMessageInfo

// MsgUpdateComplaintStatus defines the MsgUpdateComplaintStatus message.
type MsgUpdateComplaintStatus struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id          uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus   string `protobuf:"bytes,3,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	PublicNotes string `protobuf:"bytes,4,opt,name=public_notes,json=publicNotes,proto3" json:"public_notes,omitempty"`
}

func (m *MsgUpdateComplaintStatus) Reset()         { *m = MsgUpdateComplaintStatus{} }
func (m *MsgUpdateComplaintStatus) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateComplaintStatus) ProtoMessage()    {}
func (*MsgUpdateComplaintStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{6}
}
func (m *MsgUpdateComplaintStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateComplaintStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateComplaintStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateComplaintStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateComplaintStatus.Merge(m, src)
}
func (m *MsgUpdateComplaintStatus) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateComplaintStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateComplaintStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateComplaintStatus proto.InternalMessageInfo

func (m *MsgUpdateComplaintStatus) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateComplaintStatus) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateComplaintStatus) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

func (m *MsgUpdateComplaintStatus) GetPublicNotes() string {
	if m != nil {
		return m.PublicNotes
	}
	return ""
}

// MsgUpdateComplaintStatusResponse defines the MsgUpdateComplaintStatusResponse message.
type MsgUpdateComplaintStatusResponse struct {
}

func (m *MsgUpdateComplaintStatusResponse) Reset()         { *m = MsgUpdateComplaintStatusResponse{} }
func (m *MsgUpdateComplaintStatusResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateComplaintStatusResponse) ProtoMessage()    {}
func (*MsgUpdateComplaintStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_764b2987a200c6e4, []int{7}
}
func (m *MsgUpdateComplaintStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateComplaintStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateComplaintStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateComplaintStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateComplaintStatusResponse.Merge(m, src)
}
func (m *MsgUpdateComplaintStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateComplaintStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateComplaintStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateComplaintStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "sawtak.sawtak.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "sawtak.sawtak.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSubmitIdentifiedComplaint)(nil), "sawtak.sawtak.v1.MsgSubmitIdentifiedComplaint")
	proto.RegisterType((*MsgSubmitIdentifiedComplaintResponse)(nil), "sawtak.sawtak.v1.MsgSubmitIdentifiedComplaintResponse")
	proto.RegisterType((*MsgSubmitAnonymousComplaint)(nil), "sawtak.sawtak.v1.MsgSubmitAnonymousComplaint")
	proto.RegisterType((*MsgSubmitAnonymousComplaintResponse)(nil), "sawtak.sawtak.v1.MsgSubmitAnonymousComplaintResponse")
	proto.RegisterType((*MsgUpdateComplaintStatus)(nil), "sawtak.sawtak.v1.MsgUpdateComplaintStatus")
	proto.RegisterType((*MsgUpdateComplaintStatusResponse)(nil), "sawtak.sawtak.v1.MsgUpdateComplaintStatusResponse")
}

func init() { proto.RegisterFile("sawtak/sawtak/v1/tx.proto", fileDescriptor_764b2987a200c6e4) }

var fileDescriptor_764b2987a200c6e4 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0xd3, 0x9f, 0x79, 0x0d, 0xbf, 0x4c, 0x50, 0x1d, 0xd3, 0xa6, 0x6d, 0x0a, 0xa8, 0x44,
	0x6a, 0xac, 0x06, 0xd1, 0xa1, 0x4c, 0x2d, 0x0c, 0x74, 0x28, 0x82, 0x14, 0x16, 0x84, 0x14, 0x5d,
	0xec, 0xab, 0x7b, 0x6a, 0x7c, 0x67, 0xdd, 0x5d, 0x9a, 0x66, 0xab, 0x60, 0x63, 0xe2, 0xcf, 0x60,
	0x42, 0x1d, 0x98, 0x90, 0xd8, 0x3b, 0x56, 0x4c, 0x4c, 0x08, 0xb5, 0x48, 0x5d, 0xf8, 0x23, 0x90,
	0xed, 0xb3, 0x2b, 0xdc, 0x26, 0xa5, 0x30, 0xb1, 0x24, 0x7e, 0xdf, 0xfb, 0xee, 0xbd, 0xef, 0x7d,
	0x67, 0xdf, 0x41, 0x51, 0xa0, 0x8e, 0x44, 0x5b, 0x96, 0xfa, 0xdb, 0x5e, 0xb0, 0xe4, 0x4e, 0xd5,
	0xe7, 0x4c, 0x32, 0xfd, 0x6a, 0x84, 0x55, 0xd5, 0xdf, 0xf6, 0x82, 0x79, 0x0d, 0x79, 0x84, 0x32,
	0x2b, 0xfc, 0x8d, 0x48, 0xe6, 0xb8, 0xcd, 0x84, 0xc7, 0x84, 0xe5, 0x09, 0x37, 0x58, 0xec, 0x09,
	0x57, 0x25, 0x8a, 0x51, 0xa2, 0x11, 0x46, 0x56, 0x14, 0xa8, 0x54, 0xc1, 0x65, 0x2e, 0x8b, 0xf0,
	0xe0, 0x49, 0xa1, 0x13, 0x2e, 0x63, 0x6e, 0x0b, 0x5b, 0xc8, 0x27, 0x16, 0xa2, 0x94, 0x49, 0x24,
	0x09, 0xa3, 0xf1, 0x9a, 0xc9, 0x53, 0x3a, 0x7d, 0xc4, 0x91, 0xa7, 0xd2, 0xe5, 0x4f, 0x1a, 0x5c,
	0x59, 0x13, 0xee, 0x0b, 0xdf, 0x41, 0x12, 0x3f, 0x0d, 0x33, 0xfa, 0x22, 0xe4, 0x50, 0x5b, 0x6e,
	0x32, 0x4e, 0x64, 0xd7, 0xd0, 0xa6, 0xb5, 0xb9, 0xdc, 0x8a, 0xf1, 0xe5, 0xe3, 0x7c, 0x41, 0x69,
	0x59, 0x76, 0x1c, 0x8e, 0x85, 0x58, 0x97, 0x9c, 0x50, 0xb7, 0x7e, 0x42, 0xd5, 0x1f, 0xc0, 0x70,
	0x54, 0xdb, 0xc8, 0x4e, 0x6b, 0x73, 0x63, 0x35, 0xa3, 0x9a, 0x36, 0xa2, 0x1a, 0x75, 0x58, 0xc9,
	0xed, 0x7f, 0x9b, 0xca, 0xbc, 0x3f, 0xde, 0xab, 0x68, 0x75, 0xb5, 0x64, 0xa9, 0xf6, 0xfa, 0x78,
	0xaf, 0x72, 0x52, 0xec, 0xed, 0xf1, 0x5e, 0x65, 0x4a, 0x69, 0xde, 0x89, 0xc5, 0xa7, 0x84, 0x96,
	0x8b, 0x30, 0x9e, 0x82, 0xea, 0x58, 0xf8, 0x8c, 0x0a, 0x5c, 0xfe, 0x9c, 0x85, 0x89, 0x35, 0xe1,
	0xae, 0xb7, 0x9b, 0x1e, 0x91, 0xab, 0x0e, 0xa6, 0x92, 0x6c, 0x10, 0xec, 0x3c, 0x64, 0x9e, 0xdf,
	0x42, 0x84, 0x4a, 0xbd, 0x06, 0x23, 0x36, 0xc7, 0x48, 0x32, 0x7e, 0xee, 0x88, 0x31, 0x51, 0x9f,
	0x82, 0x31, 0xc9, 0x91, 0xbd, 0x45, 0xa8, 0xdb, 0x20, 0x4e, 0x38, 0x65, 0xae, 0x0e, 0x31, 0xb4,
	0xea, 0xe8, 0x05, 0x18, 0x92, 0x44, 0xb6, 0xb0, 0x31, 0x10, 0xa6, 0xa2, 0x40, 0xd7, 0x61, 0x50,
	0xe2, 0x1d, 0x69, 0x0c, 0x86, 0x60, 0xf8, 0xac, 0x9b, 0x30, 0x6a, 0x23, 0x89, 0x5d, 0xc6, 0xbb,
	0xc6, 0x50, 0x88, 0x27, 0x71, 0xc0, 0x47, 0x1c, 0x23, 0x63, 0x38, 0xe2, 0x07, 0xcf, 0x41, 0x6b,
	0x87, 0x70, 0x6c, 0x4b, 0xec, 0x34, 0x24, 0x33, 0x46, 0xa2, 0xd6, 0x31, 0xf4, 0x9c, 0xe9, 0xb3,
	0x70, 0x89, 0x50, 0x9b, 0x04, 0x93, 0x36, 0x02, 0x3f, 0x8c, 0xd1, 0x90, 0x92, 0x8f, 0xc1, 0x47,
	0x48, 0xe2, 0xa0, 0x2b, 0xde, 0x0e, 0x42, 0x1b, 0x1b, 0xb9, 0xa8, 0x6b, 0x1c, 0x2f, 0xe5, 0x83,
	0x0d, 0x88, 0x47, 0x2d, 0xdf, 0x81, 0x5b, 0xfd, 0xec, 0x4b, 0x7c, 0xfe, 0x91, 0x85, 0x9b, 0x09,
	0x71, 0x99, 0x32, 0xda, 0xf5, 0x58, 0x5b, 0xfc, 0x9b, 0xcd, 0x0b, 0x50, 0x40, 0x71, 0xa5, 0x06,
	0x89, 0x9b, 0x73, 0xe5, 0xf7, 0xf5, 0x24, 0x97, 0xe8, 0xe2, 0xff, 0xb3, 0xf1, 0x81, 0x76, 0x9f,
	0x33, 0xb6, 0x61, 0x40, 0xa4, 0x3d, 0x0c, 0x52, 0xdb, 0x71, 0x1b, 0x66, 0xfb, 0xb8, 0x9c, 0xec,
	0xc6, 0x07, 0x0d, 0x8c, 0xe4, 0x8b, 0x48, 0xd2, 0xeb, 0x12, 0xc9, 0xb6, 0xf8, 0xab, 0xad, 0xb8,
	0x0c, 0x59, 0xf5, 0xa2, 0x0f, 0xd6, 0xb3, 0xc4, 0xd1, 0x27, 0x01, 0x28, 0xee, 0x34, 0x44, 0x58,
	0x51, 0x99, 0x9d, 0xa3, 0xb8, 0xa3, 0x5a, 0xcc, 0x40, 0xde, 0x6f, 0x37, 0x5b, 0xc4, 0x6e, 0x50,
	0x26, 0xb1, 0x50, 0xc6, 0x8f, 0x45, 0xd8, 0x93, 0x00, 0x4a, 0xcd, 0x55, 0x86, 0xe9, 0x5e, 0x7a,
	0xe3, 0xa1, 0x6a, 0x3f, 0x07, 0x60, 0x60, 0x4d, 0xb8, 0xfa, 0x2b, 0xc8, 0xff, 0x76, 0x4c, 0xcd,
	0x9c, 0x3e, 0x5e, 0x52, 0xa7, 0x81, 0x79, 0xf7, 0x5c, 0x4a, 0xdc, 0x45, 0x7f, 0xa3, 0x41, 0xb1,
	0xf7, 0x69, 0x51, 0x3d, 0xb3, 0x50, 0x4f, 0xbe, 0xb9, 0x78, 0x31, 0x7e, 0xa2, 0x62, 0x57, 0x03,
	0xa3, 0xe7, 0xb7, 0x34, 0xdf, 0xa7, 0xe8, 0x69, 0xba, 0x79, 0xff, 0x42, 0xf4, 0x44, 0x42, 0x07,
	0x6e, 0x9c, 0xfd, 0xfe, 0x54, 0xfa, 0x98, 0x99, 0xe2, 0x9a, 0xb5, 0x3f, 0xe7, 0xc6, 0x8d, 0xcd,
	0xa1, 0xdd, 0xe0, 0x42, 0x58, 0x79, 0xbc, 0x7f, 0x58, 0xd2, 0x0e, 0x0e, 0x4b, 0xda, 0xf7, 0xc3,
	0x92, 0xf6, 0xee, 0xa8, 0x94, 0x39, 0x38, 0x2a, 0x65, 0xbe, 0x1e, 0x95, 0x32, 0x2f, 0xab, 0x2e,
	0x91, 0x9b, 0xed, 0x66, 0xd5, 0x66, 0x9e, 0x25, 0x50, 0x17, 0x3b, 0xa4, 0xc9, 0xd1, 0x26, 0xf1,
	0x9e, 0x59, 0xe9, 0x8b, 0x42, 0x76, 0x7d, 0x2c, 0x9a, 0xc3, 0xe1, 0x15, 0x77, 0xef, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x04, 0x0b, 0x46, 0xbe, 0xab, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// SubmitIdentifiedComplaint defines the SubmitIdentifiedComplaint RPC.
	SubmitIdentifiedComplaint(ctx context.Context, in *MsgSubmitIdentifiedComplaint, opts ...grpc.CallOption) (*MsgSubmitIdentifiedComplaintResponse, error)
	// SubmitAnonymousComplaint defines the SubmitAnonymousComplaint RPC.
	SubmitAnonymousComplaint(ctx context.Context, in *MsgSubmitAnonymousComplaint, opts ...grpc.CallOption) (*MsgSubmitAnonymousComplaintResponse, error)
	// UpdateComplaintStatus defines the UpdateComplaintStatus RPC.
	UpdateComplaintStatus(ctx context.Context, in *MsgUpdateComplaintStatus, opts ...grpc.CallOption) (*MsgUpdateComplaintStatusResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitIdentifiedComplaint(ctx context.Context, in *MsgSubmitIdentifiedComplaint, opts ...grpc.CallOption) (*MsgSubmitIdentifiedComplaintResponse, error) {
	out := new(MsgSubmitIdentifiedComplaintResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Msg/SubmitIdentifiedComplaint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitAnonymousComplaint(ctx context.Context, in *MsgSubmitAnonymousComplaint, opts ...grpc.CallOption) (*MsgSubmitAnonymousComplaintResponse, error) {
	out := new(MsgSubmitAnonymousComplaintResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Msg/SubmitAnonymousComplaint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateComplaintStatus(ctx context.Context, in *MsgUpdateComplaintStatus, opts ...grpc.CallOption) (*MsgUpdateComplaintStatusResponse, error) {
	out := new(MsgUpdateComplaintStatusResponse)
	err := c.cc.Invoke(ctx, "/sawtak.sawtak.v1.Msg/UpdateComplaintStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// SubmitIdentifiedComplaint defines the SubmitIdentifiedComplaint RPC.
	SubmitIdentifiedComplaint(context.Context, *MsgSubmitIdentifiedComplaint) (*MsgSubmitIdentifiedComplaintResponse, error)
	// SubmitAnonymousComplaint defines the SubmitAnonymousComplaint RPC.
	SubmitAnonymousComplaint(context.Context, *MsgSubmitAnonymousComplaint) (*MsgSubmitAnonymousComplaintResponse, error)
	// UpdateComplaintStatus defines the UpdateComplaintStatus RPC.
	UpdateComplaintStatus(context.Context, *MsgUpdateComplaintStatus) (*MsgUpdateComplaintStatusResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SubmitIdentifiedComplaint(ctx context.Context, req *MsgSubmitIdentifiedComplaint) (*MsgSubmitIdentifiedComplaintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitIdentifiedComplaint not implemented")
}
func (*UnimplementedMsgServer) SubmitAnonymousComplaint(ctx context.Context, req *MsgSubmitAnonymousComplaint) (*MsgSubmitAnonymousComplaintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAnonymousComplaint not implemented")
}
func (*UnimplementedMsgServer) UpdateComplaintStatus(ctx context.Context, req *MsgUpdateComplaintStatus) (*MsgUpdateComplaintStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComplaintStatus not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitIdentifiedComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitIdentifiedComplaint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitIdentifiedComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Msg/SubmitIdentifiedComplaint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitIdentifiedComplaint(ctx, req.(*MsgSubmitIdentifiedComplaint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitAnonymousComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitAnonymousComplaint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitAnonymousComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Msg/SubmitAnonymousComplaint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitAnonymousComplaint(ctx, req.(*MsgSubmitAnonymousComplaint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateComplaintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateComplaintStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateComplaintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sawtak.sawtak.v1.Msg/UpdateComplaintStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateComplaintStatus(ctx, req.(*MsgUpdateComplaintStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sawtak.sawtak.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SubmitIdentifiedComplaint",
			Handler:    _Msg_SubmitIdentifiedComplaint_Handler,
		},
		{
			MethodName: "SubmitAnonymousComplaint",
			Handler:    _Msg_SubmitAnonymousComplaint_Handler,
		},
		{
			MethodName: "UpdateComplaintStatus",
			Handler:    _Msg_UpdateComplaintStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sawtak/sawtak/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitIdentifiedComplaint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitIdentifiedComplaint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitIdentifiedComplaint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Evidence) > 0 {
		i -= len(m.Evidence)
		copy(dAtA[i:], m.Evidence)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Evidence)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.IncidentDate) > 0 {
		i -= len(m.IncidentDate)
		copy(dAtA[i:], m.IncidentDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IncidentDate)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DirectedTo) > 0 {
		i -= len(m.DirectedTo)
		copy(dAtA[i:], m.DirectedTo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DirectedTo)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Area) > 0 {
		i -= len(m.Area)
		copy(dAtA[i:], m.Area)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Area)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrackingId) > 0 {
		i -= len(m.TrackingId)
		copy(dAtA[i:], m.TrackingId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TrackingId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitIdentifiedComplaintResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitIdentifiedComplaintResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitIdentifiedComplaintResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitAnonymousComplaint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitAnonymousComplaint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitAnonymousComplaint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Evidence) > 0 {
		i -= len(m.Evidence)
		copy(dAtA[i:], m.Evidence)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Evidence)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.IncidentDate) > 0 {
		i -= len(m.IncidentDate)
		copy(dAtA[i:], m.IncidentDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IncidentDate)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DirectedTo) > 0 {
		i -= len(m.DirectedTo)
		copy(dAtA[i:], m.DirectedTo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DirectedTo)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Area) > 0 {
		i -= len(m.Area)
		copy(dAtA[i:], m.Area)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Area)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AnonymousIdentifier) > 0 {
		i -= len(m.AnonymousIdentifier)
		copy(dAtA[i:], m.AnonymousIdentifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AnonymousIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitAnonymousComplaintResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitAnonymousComplaintResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitAnonymousComplaintResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateComplaintStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateComplaintStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateComplaintStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicNotes) > 0 {
		i -= len(m.PublicNotes)
		copy(dAtA[i:], m.PublicNotes)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicNotes)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NewStatus) > 0 {
		i -= len(m.NewStatus)
		copy(dAtA[i:], m.NewStatus)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewStatus)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateComplaintStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateComplaintStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateComplaintStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitIdentifiedComplaint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TrackingId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Area)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DirectedTo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.IncidentDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Evidence)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitIdentifiedComplaintResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitAnonymousComplaint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AnonymousIdentifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Area)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DirectedTo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.IncidentDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Evidence)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitAnonymousComplaintResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateComplaintStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.NewStatus)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicNotes)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateComplaintStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitIdentifiedComplaint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitIdentifiedComplaint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitIdentifiedComplaint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrackingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrackingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Area", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Area = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DirectedTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DirectedTo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncidentDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncidentDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Evidence = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitIdentifiedComplaintResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitIdentifiedComplaintResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitIdentifiedComplaintResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitAnonymousComplaint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitAnonymousComplaint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitAnonymousComplaint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnonymousIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnonymousIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Area", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Area = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DirectedTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DirectedTo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncidentDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncidentDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Evidence = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitAnonymousComplaintResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitAnonymousComplaintResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitAnonymousComplaintResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateComplaintStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateComplaintStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateComplaintStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicNotes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicNotes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateComplaintStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateComplaintStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateComplaintStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
